version: "3.6"

services:
  web:
    image: orsee:3.2.0
    build:
      context: ./web
      args:
        ROOT_DIRECTORY: ${ROOT_DIRECTORY:-/orsee}
    ports:
      - 8088:80
    env_file:
      - .env
    read_only: true
    tmpfs:
      - /run
      - /var/cache
      - /var/local
      - /tmp
  db:
    image: mariadb:10.11
    volumes:
      - db:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
  mailhog:
    image: mailhog/mailhog
    volumes:
      - mailhog-maildir:/home/mailhog/maildir
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/home/mailhog/maildir
    ports:
      - 8025:8025
volumes:
  db:
  mailhog-maildir:
